#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum ObjType {
    Unknown,
    CanMessage,
    CanError,
    CanOverload,
    CanStatistic,
    AppTrigger,
    EnvInteger,
    EnvDouble,
    EnvString,
    EnvData,
    LogContainer,
    LinMessage,
    LinCrcError,
    LinDlcInfo,
    LinRcvError,
    LinSndError,
    LinSlvTimeout,
    LinSchedModch,
    LinSynError,
    LinBaudrate,
    LinSleep,
    LinWakeup,
    MostSpy,
    MostCtrl,
    MostLightlock,
    MostStatistic,
    Reserved26,
    Reserved27,
    Reserved28,
    FlexrayData,
    FlexraySync,
    CanDriverError,
    MostPkt,
    MostPkt2,
    MostHwmode,
    MostReg,
    MostGenreg,
    MostNetstate,
    MostDatalost,
    MostTrigger,
    FlexrayCycle,
    FlexrayMessage,
    LinChecksumInfo,
    LinSpikeEvent,
    CanDriverSync,
    FlexrayStatus,
    GpsEvent,
    FrError,
    FrStatus,
    FrStartcycle,
    FrRcvmessage,
    Realtimeclock,
    Reserved52,
    Reserved53,
    LinStatistic,
    J1708Message,
    J1708VirtualMsg,
    LinMessage2,
    LinSndError2,
    LinSynError2,
    LinCrcError2,
    LinRcvError2,
    LinWakeup2,
    LinSpikeEvent2,
    LinLongDomSig,
    AppText,
    FrRcvmessageEx,
    MostStatisticex,
    MostTxlight,
    MostAlloctab,
    MostStress,
    EthernetFrame,
    SysVariable,
    CanErrorExt,
    CanDriverErrorExt,
    LinLongDomSig2,
    Most150Message,
    Most150Pkt,
    MostEthernetPkt,
    Most150MessageFragment,
    Most150PktFragment,
    MostEthernetPktFragment,
    MostSystemEvent,
    Most150Alloctab,
    Most50Message,
    Most50Pkt,
    CanMessage2,
    LinUnexpectedWakeup,
    LinShortOrSlowResponse,
    LinDisturbanceEvent,
    SerialEvent,
    OverrunError,
    EventComment,
    WlanFrame,
    WlanStatistic,
    MostEcl,
    GlobalMarker,
    AfdxFrame,
    AfdxStatistic,
    KlineStatusevent,
    CanFdMessage,
    CanFdMessage64,
    EthernetRxError,
    EthernetStatus,
    CanFdError64,
    LinShortOrSlowResponse2,
    AfdxStatus,
    AfdxBusStatistic,
    Reserved108,
    AfdxErrorEvent,
    A429Error,
    A429Status,
    A429BusStatistic,
    A429Message,
    EthernetStatistic,
    Unknown115,
    Reserved116,
    Reserved117,
    TestStructure,
    DiagRequestInterpretation,
    EthernetFrameEx,
    EthernetFrameForwarded,
    EthernetErrorEx,
    EthernetErrorForwarded,
    FunctionBus,
    DataLostBegin,
    DataLostEnd,
    WaterMarkEvent,
    TriggerCondition,
    CanSettingChanged,
    DistributedObjectMember,
    AttributeEvent,
    Other(u32),
}

impl ObjType {
    pub fn from_u32(v: u32) -> Self {
        match v {
            0 => Self::Unknown,
            1 => Self::CanMessage,
            2 => Self::CanError,
            3 => Self::CanOverload,
            4 => Self::CanStatistic,
            5 => Self::AppTrigger,
            6 => Self::EnvInteger,
            7 => Self::EnvDouble,
            8 => Self::EnvString,
            9 => Self::EnvData,
            10 => Self::LogContainer,
            11 => Self::LinMessage,
            12 => Self::LinCrcError,
            13 => Self::LinDlcInfo,
            14 => Self::LinRcvError,
            15 => Self::LinSndError,
            16 => Self::LinSlvTimeout,
            17 => Self::LinSchedModch,
            18 => Self::LinSynError,
            19 => Self::LinBaudrate,
            20 => Self::LinSleep,
            21 => Self::LinWakeup,
            22 => Self::MostSpy,
            23 => Self::MostCtrl,
            24 => Self::MostLightlock,
            25 => Self::MostStatistic,
            26 => Self::Reserved26,
            27 => Self::Reserved27,
            28 => Self::Reserved28,
            29 => Self::FlexrayData,
            30 => Self::FlexraySync,
            31 => Self::CanDriverError,
            32 => Self::MostPkt,
            33 => Self::MostPkt2,
            34 => Self::MostHwmode,
            35 => Self::MostReg,
            36 => Self::MostGenreg,
            37 => Self::MostNetstate,
            38 => Self::MostDatalost,
            39 => Self::MostTrigger,
            40 => Self::FlexrayCycle,
            41 => Self::FlexrayMessage,
            42 => Self::LinChecksumInfo,
            43 => Self::LinSpikeEvent,
            44 => Self::CanDriverSync,
            45 => Self::FlexrayStatus,
            46 => Self::GpsEvent,
            47 => Self::FrError,
            48 => Self::FrStatus,
            49 => Self::FrStartcycle,
            50 => Self::FrRcvmessage,
            51 => Self::Realtimeclock,
            52 => Self::Reserved52,
            53 => Self::Reserved53,
            54 => Self::LinStatistic,
            55 => Self::J1708Message,
            56 => Self::J1708VirtualMsg,
            57 => Self::LinMessage2,
            58 => Self::LinSndError2,
            59 => Self::LinSynError2,
            60 => Self::LinCrcError2,
            61 => Self::LinRcvError2,
            62 => Self::LinWakeup2,
            63 => Self::LinSpikeEvent2,
            64 => Self::LinLongDomSig,
            65 => Self::AppText,
            66 => Self::FrRcvmessageEx,
            67 => Self::MostStatisticex,
            68 => Self::MostTxlight,
            69 => Self::MostAlloctab,
            70 => Self::MostStress,
            71 => Self::EthernetFrame,
            72 => Self::SysVariable,
            73 => Self::CanErrorExt,
            74 => Self::CanDriverErrorExt,
            75 => Self::LinLongDomSig2,
            76 => Self::Most150Message,
            77 => Self::Most150Pkt,
            78 => Self::MostEthernetPkt,
            79 => Self::Most150MessageFragment,
            80 => Self::Most150PktFragment,
            81 => Self::MostEthernetPktFragment,
            82 => Self::MostSystemEvent,
            83 => Self::Most150Alloctab,
            84 => Self::Most50Message,
            85 => Self::Most50Pkt,
            86 => Self::CanMessage2,
            87 => Self::LinUnexpectedWakeup,
            88 => Self::LinShortOrSlowResponse,
            89 => Self::LinDisturbanceEvent,
            90 => Self::SerialEvent,
            91 => Self::OverrunError,
            92 => Self::EventComment,
            93 => Self::WlanFrame,
            94 => Self::WlanStatistic,
            95 => Self::MostEcl,
            96 => Self::GlobalMarker,
            97 => Self::AfdxFrame,
            98 => Self::AfdxStatistic,
            99 => Self::KlineStatusevent,
            100 => Self::CanFdMessage,
            101 => Self::CanFdMessage64,
            102 => Self::EthernetRxError,
            103 => Self::EthernetStatus,
            104 => Self::CanFdError64,
            105 => Self::LinShortOrSlowResponse2,
            106 => Self::AfdxStatus,
            107 => Self::AfdxBusStatistic,
            108 => Self::Reserved108,
            109 => Self::AfdxErrorEvent,
            110 => Self::A429Error,
            111 => Self::A429Status,
            112 => Self::A429BusStatistic,
            113 => Self::A429Message,
            114 => Self::EthernetStatistic,
            115 => Self::Unknown115,
            116 => Self::Reserved116,
            117 => Self::Reserved117,
            118 => Self::TestStructure,
            119 => Self::DiagRequestInterpretation,
            120 => Self::EthernetFrameEx,
            121 => Self::EthernetFrameForwarded,
            122 => Self::EthernetErrorEx,
            123 => Self::EthernetErrorForwarded,
            124 => Self::FunctionBus,
            125 => Self::DataLostBegin,
            126 => Self::DataLostEnd,
            127 => Self::WaterMarkEvent,
            128 => Self::TriggerCondition,
            129 => Self::CanSettingChanged,
            130 => Self::DistributedObjectMember,
            131 => Self::AttributeEvent,
            _ => Self::Other(v),
        }
    }

    pub fn to_u32(self) -> u32 {
        match self {
            Self::Unknown => 0,
            Self::CanMessage => 1,
            Self::CanError => 2,
            Self::CanOverload => 3,
            Self::CanStatistic => 4,
            Self::AppTrigger => 5,
            Self::EnvInteger => 6,
            Self::EnvDouble => 7,
            Self::EnvString => 8,
            Self::EnvData => 9,
            Self::LogContainer => 10,
            Self::LinMessage => 11,
            Self::LinCrcError => 12,
            Self::LinDlcInfo => 13,
            Self::LinRcvError => 14,
            Self::LinSndError => 15,
            Self::LinSlvTimeout => 16,
            Self::LinSchedModch => 17,
            Self::LinSynError => 18,
            Self::LinBaudrate => 19,
            Self::LinSleep => 20,
            Self::LinWakeup => 21,
            Self::MostSpy => 22,
            Self::MostCtrl => 23,
            Self::MostLightlock => 24,
            Self::MostStatistic => 25,
            Self::Reserved26 => 26,
            Self::Reserved27 => 27,
            Self::Reserved28 => 28,
            Self::FlexrayData => 29,
            Self::FlexraySync => 30,
            Self::CanDriverError => 31,
            Self::MostPkt => 32,
            Self::MostPkt2 => 33,
            Self::MostHwmode => 34,
            Self::MostReg => 35,
            Self::MostGenreg => 36,
            Self::MostNetstate => 37,
            Self::MostDatalost => 38,
            Self::MostTrigger => 39,
            Self::FlexrayCycle => 40,
            Self::FlexrayMessage => 41,
            Self::LinChecksumInfo => 42,
            Self::LinSpikeEvent => 43,
            Self::CanDriverSync => 44,
            Self::FlexrayStatus => 45,
            Self::GpsEvent => 46,
            Self::FrError => 47,
            Self::FrStatus => 48,
            Self::FrStartcycle => 49,
            Self::FrRcvmessage => 50,
            Self::Realtimeclock => 51,
            Self::Reserved52 => 52,
            Self::Reserved53 => 53,
            Self::LinStatistic => 54,
            Self::J1708Message => 55,
            Self::J1708VirtualMsg => 56,
            Self::LinMessage2 => 57,
            Self::LinSndError2 => 58,
            Self::LinSynError2 => 59,
            Self::LinCrcError2 => 60,
            Self::LinRcvError2 => 61,
            Self::LinWakeup2 => 62,
            Self::LinSpikeEvent2 => 63,
            Self::LinLongDomSig => 64,
            Self::AppText => 65,
            Self::FrRcvmessageEx => 66,
            Self::MostStatisticex => 67,
            Self::MostTxlight => 68,
            Self::MostAlloctab => 69,
            Self::MostStress => 70,
            Self::EthernetFrame => 71,
            Self::SysVariable => 72,
            Self::CanErrorExt => 73,
            Self::CanDriverErrorExt => 74,
            Self::LinLongDomSig2 => 75,
            Self::Most150Message => 76,
            Self::Most150Pkt => 77,
            Self::MostEthernetPkt => 78,
            Self::Most150MessageFragment => 79,
            Self::Most150PktFragment => 80,
            Self::MostEthernetPktFragment => 81,
            Self::MostSystemEvent => 82,
            Self::Most150Alloctab => 83,
            Self::Most50Message => 84,
            Self::Most50Pkt => 85,
            Self::CanMessage2 => 86,
            Self::LinUnexpectedWakeup => 87,
            Self::LinShortOrSlowResponse => 88,
            Self::LinDisturbanceEvent => 89,
            Self::SerialEvent => 90,
            Self::OverrunError => 91,
            Self::EventComment => 92,
            Self::WlanFrame => 93,
            Self::WlanStatistic => 94,
            Self::MostEcl => 95,
            Self::GlobalMarker => 96,
            Self::AfdxFrame => 97,
            Self::AfdxStatistic => 98,
            Self::KlineStatusevent => 99,
            Self::CanFdMessage => 100,
            Self::CanFdMessage64 => 101,
            Self::EthernetRxError => 102,
            Self::EthernetStatus => 103,
            Self::CanFdError64 => 104,
            Self::LinShortOrSlowResponse2 => 105,
            Self::AfdxStatus => 106,
            Self::AfdxBusStatistic => 107,
            Self::Reserved108 => 108,
            Self::AfdxErrorEvent => 109,
            Self::A429Error => 110,
            Self::A429Status => 111,
            Self::A429BusStatistic => 112,
            Self::A429Message => 113,
            Self::EthernetStatistic => 114,
            Self::Unknown115 => 115,
            Self::Reserved116 => 116,
            Self::Reserved117 => 117,
            Self::TestStructure => 118,
            Self::DiagRequestInterpretation => 119,
            Self::EthernetFrameEx => 120,
            Self::EthernetFrameForwarded => 121,
            Self::EthernetErrorEx => 122,
            Self::EthernetErrorForwarded => 123,
            Self::FunctionBus => 124,
            Self::DataLostBegin => 125,
            Self::DataLostEnd => 126,
            Self::WaterMarkEvent => 127,
            Self::TriggerCondition => 128,
            Self::CanSettingChanged => 129,
            Self::DistributedObjectMember => 130,
            Self::AttributeEvent => 131,
            Self::Other(v) => v,
        }
    }

    pub fn is_padding_needed(&self) -> bool {
        matches!(
            self,
            ObjType::Unknown
                | ObjType::LogContainer
                | ObjType::MostPkt
                | ObjType::MostPkt2
                | ObjType::AppText
                | ObjType::MostAlloctab
                | ObjType::EthernetFrame
                | ObjType::SysVariable
                | ObjType::Most150Message
                | ObjType::Most150Pkt
                | ObjType::MostEthernetPkt
                | ObjType::Most150MessageFragment
                | ObjType::Most150PktFragment
                | ObjType::MostEthernetPktFragment
                | ObjType::Most150Alloctab
                | ObjType::Most50Message
                | ObjType::Most50Pkt
                | ObjType::SerialEvent
                | ObjType::EventComment
                | ObjType::WlanFrame
                | ObjType::GlobalMarker
                | ObjType::AfdxFrame
                | ObjType::EthernetRxError
        )
    }
}
